# Generated by Django 4.0.3 on 2022-03-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # dependencies = [
    #     ('comments', '0004_remove_comment_reply'),
    #     migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    #     ('replies', '0002_remove_reply_comment_remove_reply_user'),
    # ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default='not null', on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
