# Generated by Django 4.0.3 on 2022-03-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_remove_reply_comment_remove_reply_user'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='replies.reply'),
            preserve_default=False,
        ),
    ]
